// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADSSsKfwEecfRzu8wt5Y4IswkW8mF9rSs',
    appId: '1:181370278647:web:c3b6aa51c12c439752b9f2',
    messagingSenderId: '181370278647',
    projectId: 'projmatch-ce9a9',
    authDomain: 'projmatch-ce9a9.firebaseapp.com',
    storageBucket: 'projmatch-ce9a9.appspot.com',
    measurementId: 'G-MBSKG2C24P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlAUWUa2r0GjSzy02OwQLhxbiK9pPFFRA',
    appId: '1:181370278647:android:a6c98b8803490f5252b9f2',
    messagingSenderId: '181370278647',
    projectId: 'projmatch-ce9a9',
    storageBucket: 'projmatch-ce9a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn9C5g5DjDVks5DfHTsefdjWSqwl7erWQ',
    appId: '1:181370278647:ios:a2988fd1b58b712f52b9f2',
    messagingSenderId: '181370278647',
    projectId: 'projmatch-ce9a9',
    storageBucket: 'projmatch-ce9a9.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn9C5g5DjDVks5DfHTsefdjWSqwl7erWQ',
    appId: '1:181370278647:ios:a2988fd1b58b712f52b9f2',
    messagingSenderId: '181370278647',
    projectId: 'projmatch-ce9a9',
    storageBucket: 'projmatch-ce9a9.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADSSsKfwEecfRzu8wt5Y4IswkW8mF9rSs',
    appId: '1:181370278647:web:cc19c5ad7390dc4152b9f2',
    messagingSenderId: '181370278647',
    projectId: 'projmatch-ce9a9',
    authDomain: 'projmatch-ce9a9.firebaseapp.com',
    storageBucket: 'projmatch-ce9a9.appspot.com',
    measurementId: 'G-JCPRT809S9',
  );
}
